# Generated by Django 5.0.4 on 2026-01-15 10:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file to Cloudinary', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sermon_audio'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='feature_pic',
            field=models.ImageField(default='feature_default.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sermon_images'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='link',
            field=models.URLField(blank=True, help_text='Legacy Telegram link (optional)', null=True, unique=True),
        ),
    ]
