# Generated by Django 5.0.4 on 2026-01-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_audio_file_alter_sermon_feature_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='link',
        ),
    ]
