# Generated by Django 4.2.9 on 2024-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True)),
                ('feature_pic', models.ImageField(default='feature_default.jpg', upload_to='newsevent_images')),
                ('content_pic', models.ImageField(default='content_default.jpg', upload_to='newsevent_images')),
            ],
        ),
    ]
