# Generated by Django 5.0.4 on 2026-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='daily_bible_reading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='week_teaching',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
