# Generated by Django 5.0.4 on 2026-01-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotionals', '0002_alter_devotional_daily_bible_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotional',
            name='daily_bible_reading',
        ),
        migrations.RemoveField(
            model_name='devotional',
            name='reference_text',
        ),
        migrations.RemoveField(
            model_name='devotional',
            name='week_teaching',
        ),
    ]
