# Generated by Django 5.0.1 on 2024-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sermons',
            name='date_preached',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sermons',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
