# Generated by Django 5.0.1 on 2024-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0002_newsevents_content_sermons_date_preached_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True)),
                ('picture', models.URLField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sermons',
            new_name='Sermon',
        ),
        migrations.DeleteModel(
            name='NewsEvents',
        ),
    ]
