# Generated by Django 5.0.1 on 2024-01-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0003_newsevent_rename_sermons_sermon_delete_newsevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('details', models.TextField(blank=True)),
                ('feature_pic', models.ImageField(default='feature_default.jpg', upload_to='service_images')),
                ('content_pic', models.ImageField(default='content_default.jpg', upload_to='service_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='newsevent',
            name='picture',
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content_pic1',
            field=models.ImageField(default='content_default.jpg', upload_to='newsevent_images'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content_pic2',
            field=models.ImageField(default='content_default.jpg', upload_to='newsevent_images'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='feature_pic',
            field=models.ImageField(default='feature_default.jpg', upload_to='newsevent_images'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='feature_pic',
            field=models.ImageField(default='feature_default.jpg', upload_to='sermon_images'),
        ),
    ]
