# Generated by Django 5.0.1 on 2024-01-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0004_service_details_remove_newsevent_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Details',
            new_name='Service',
        ),
    ]
