# Generated by Django 4.2.9 on 2024-02-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0007_devotional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotional',
            old_name='details',
            new_name='contents',
        ),
    ]
