# Generated by Django 5.0.4 on 2024-05-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0008_rename_details_devotional_contents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devotional',
        ),
        migrations.DeleteModel(
            name='NewsEvent',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
