# Generated by Django 5.0.4 on 2026-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swbc', '0009_delete_devotional_delete_newsevent_delete_sermon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='service',
            name='day',
            field=models.CharField(blank=True, help_text='e.g., Sundays, Wednesdays, Saturdays', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for displaying services (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('weekly', 'Weekly Service'), ('special', 'Special Service')], default='special', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(blank=True, help_text='e.g., 8:00AM, 5:30PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('title', 'service_type')},
        ),
    ]
